shader_type canvas_item;
uniform float speed = 0.005;
void vertex() {
	// Called for every vertex the material is visible on.
	VERTEX.x += cos(VERTEX.x*TIME*speed);
	VERTEX.y += sin(VERTEX.y*TIME*speed);
}

void fragment() {
	// Called for every pixel the material is visible on.
}

//void light() {
//	// Called for every pixel for every light affecting the CanvasItem.
//	// Uncomment to replace the default light processing function with this one.
//}
